name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
    
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: $DOCKER_USER
        password: $DOCKER_PASSWORD

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        build-args: 
          DB_URL=${{ secrets.DB_URL }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        context: .
        file: ./Dockerfile
        push: true
        tags: $DOCKER_USER/hair-pass-app:${{github.ref_name}}
